@startuml
'https://plantuml.com/class-diagram

skinparam class {
BackgroundColor LightGrey
ArrowColor Black
BorderColor Black
BackgroundColor<<Foo>> DarkGrey
}

skinparam backgroundcolor Gray
skinparam stereotypeCBackgroundColor YellowGreen

class Brickanoid {
-AMOUNT_OF_LEVELS : int
-STARTING_AMOUNT_OF_LIVES : int
-SCREEN_WIDTH : int
-SCREEN_HEIGHT : int
-STARTING_AMOUNT_OF_BRICKS : int
-LEVEL_BRICK_MULTIPLIER : int
-player : Paddle
-level1 : Level
-level2 : Level
-level3 : Level
-ball : Ball
-screenWidth : int
-screenHeight : int
- currentLevelCount : int
- isGameOngoing : boolean
- playerWon : boolean
+ bricksInLevels : int[]
+ {static} allLevels : ArrayList<Level>
+ {static} score : int
+ {static} lives : int
+ {static} highscore : int
+ {static} liveText : OverlayText
+ {static} scoreText : OverlayText
+ {static} highscoreText : OverlayText
+ {static} currentLevel : Level
- overlay : Overlay
+ {static} currentLevel : Level
-currentLevelCount : int
+ {static} allLevels : ArrayList<Level>
- bricksInLevels : int[]
+main(args : String[]) : void
+setupGame() : void
+setupScenes() : void
+setActiveScene(id : int) : void
+getIsGameOngoing() : boolean
+setGameIsOngoing(isGameOngoing : boolean) : void
+instantiateGameObjects() : void
+instantiateLevels() : void
+instantiateOverlayAndText() : void
+resetLevelsArray() : void
+addLevelsToGame() : void
+removeGameObjects() : void
+resetGameVariables() : void
+restartGameState() : void
+startNewGame() : void
+restartLevels() : void
+skipToNextLevel() : void
+ {static} updateHighscore() : void
+endGameAfterLoss() : void
+getHighscoreFromText() : void
+ {static} replaceHighscore(replaceWith : String) : void
+ getSCREEN_WIDTH() : int
+ getSCREEN_HEIGHT() : int
+ getPlayerWon() : boolean
+ setPlayerWon(playerWon : boolean) : void
}

class Paddle {
- MOVEMENT_SPEED : int
- GRAVITY : double
- FRICTION : double
-lives : int
-brickanoid : Brickanoid
+Paddle(initialLocation : Coordinate2D, brickanoid : Brickanoid, lives : int) : Paddle
+notifyBoundaryTouching(border : SceneBorder) : void
+onPressedKeysChange(pressedKeys : Set<KeyCode>) : void
+onCollision(collider : Collider) : void
+resetGravityAndFriction() : void
+getLives() : int
+setLives() : void
+onMouseMoved(coordinate2D : Coordinate2D) : void
}

class Brick {
-LOWEST_HP : int
-HIGHEST_HP : int
- SCORE_MULTIPLIER : int
- scoreValue : int
-hitPoints : int
+Brick(initialLocation : Coordinate2D, size : Size, resource : String) : Brick
+onCollision(collidingObject : Collider) : void
+getHitPoints() : int
+getScoreValue() : int
+ {abstract} removeBrickFromField() : void
}

/' class BrickSprite {
#BlickSprite(resource : String, initialLocation : Coordinate2D) : BrickSprite
} '/

class PowerupBrick {
+ PowerupBrick(initialLocation: Coordinate2D, size : Size, resource: String) : PowerupBrick
+ removeBrickFromField() : void
+ dropPowerup() : void
}

class SimpleBrick {
SimpleBrick(initialLocation : Coordinate2D, size : Size, resource : String)
removeBrickFromField() : void
}

class GenerateBrickTileMap {
+GenerateBrickTileMap(location : Coordinate2D, size : Size, amountOfBricks : int) : GenerateBrickTileMap
+generateTileMap(amountOfRows : int, amountOfColumns : int, amountOfBricks : int) : int[][]
+fillBricklistWithBricks(brickList : int[], brickColor : int, numberOfDifferentBricks : int) : int[]
+shuffleArray(array : int[], amountOfNumbers : int) : int[]
+defineMap() : int[][]
}

class RandomNumber {
+RandomNumber(lowerBound : int, upperBound : int) : RandomNumber
+getValue() : int
}

class MainText {
+MainText(initialLocation : Coordinate2D, text : String) : Maintext
}

class OverlayText {
+OverlayText(initialLocation : Coordinate2D, text : String, value : int) : OverlayText
+setOverlayText(sentValue : int) : void
}
class Ball {
- GRAVITY : double
- FRICTION : double
- speed : int
- direction : int
- brickanoid : Brickanoid
- powerupHitBricksCounter : int
+ {static} amountOfBallsOnScreen : int
- slowDownActive : boolean
+Ball(initialLocation : Coordinate2D, brickanoid : Brickanoid, speed : int, direction : int) : Ball
+onCollision(collider : Collider) : void
+notifyBoundaryCrossing(SceneBorder border) : void
+notifyBoundaryTouching(SceneBorder border) : void
+setSpeed(speed : int) : void
+activateSlowdown(powerup : Powerup) : void
+deactiveSlowdown() : void
+resetBall() : void
+resetLocation : void
+generateRandomDirection() : void
}

class Overlay {
-scoreText : TextEntity
-highscoreText : TextEntity
-lifeText : TextEntity
-brickanoid : Brickanoid
+Overlay(location : Coordinate2D, brickanoid : Brickanoid, lifeText : OverlayText, scoreText : OverlayText, highscoreText : OverlayText) : Overlay
+getScoreText() : TextEntity
+getHighscoreText() : TextEntity
+getLifeText() : TextEntity
}

abstract class MenuButton {
+FONTWEIGHT : int
#Brickanoid : brickanoid
+MenuButton(text : String, initialLocation : Coordinate2D, brickanoid : Brickanoid) : MenuButton
+onMouseEntered() : void
+onMouseExited() : void
}

class TextEntity #Physical {

}

class Level {
- ball : Ball
- brickanoid : Brickanoid
- player : Paddle
- overlay : Overlay
- aantalBricks : int
- tiles : BrickTilemap
- backgroundImage : String
+Level(brickanoid : Brickanoid, player : Paddle, ball : Ball, overlay : Overlay, aantalBricks : int, backgroundImage : String) : Level
+setupScene() : void
+setupEntities() : void
+setupTileMaps() : void
+getRemainingBrickCount(): int
+determineLevelStatus(brick : Brick) : void
+addEntity(yaegerEntity : YaegerEntity) : void
}

class BrickTilemap {
+BrickTilemap(location : Coordinate2D, size : Size, ) : BrickTilemap
+setupEntities() : void
+defineMap() : int[][]
}

class MenuScene {
-Brickanoid : brickanoid
+MenuScene(brickanoid : Brickanoid) : MenuScene
+setupScene() : void
+setupEntities() : void
+setCursor() : void
+getWidth() : double
+getHeight() : double
}

class PlayButton {
+PlayButton(text : String, initialLocation : Coordinate2D, brickanoid : Brickanoid)
+onMouseButtonPressed(mouseButton : MouseButton, coordinate2D : Coordinate2D)
}

class QuitButton {
+QuitButton(text : String, initialLocation : Coordinate2D, brickanoid : Brickanoid)
+onMouseButtonPressed(mouseButton : MouseButton, coordinate2D Coordinate2D) : void
}

class PowerupMultiball {
+PowerupMultiball(initialLocation : Coordinate2D) : PowerupMultiball
+activatePowerup() : void
}

class PowerupSlowdownBall {
+PowerupSlowdownBall(initialLocation : Coordinate2D) : PowerupSlowdownBall
+activatePowerup() : void
}

class PowerupExtraLife {
+PowerupExtraLife(initialLocation : Coordinate2D)
+activePowerup() : void
}

class GameOverScene {
-brickanoid : Brickanoid
+GameOverScene(brickanoid : Brickanoid) : Brickanoid
+setupScene() : void
+setupEntities() : void
}


abstract class Powerup {
+Powerup(resource : String,initialLocation : Coordinate2D) : Powerup
+ {abstract} activatePowerup() : void
+onCollision(collider : Collider) : void
}

abstract class YaegerGame #Physical {

}

abstract class DynamicScene #Physical {

}

abstract class StaticScene #Physical {

}

abstract class DynamicSpriteEntity #Physical {

}

abstract class DynamicTextEntity #Physical {

}


abstract class TileMap #Physical {

}

interface Collider #Physical {

}

interface Collided #Physical {

}

interface KeyListener #Physical {

}

interface SceneBorderTouchingWatcher #Physical {

}

interface SceneBorderCrossingWatcher #Physical {

}

interface Newtonian #Physical {

}

interface MouseButtonPressedListener #Physical {

}

interface MouseEnterListener #Physical{

}

interface MouseExitListener #Physical{

}

interface TileMapContainer #Physical {

}

interface MouseMovedListener #Physical {

}

YaegerGame <|.. Brickanoid
Level "1..*" <-- "1" Brickanoid
MenuScene "1..*" <-- "1" Brickanoid
GameOverScene "1" <-- "1" Brickanoid
Paddle "1" <-- "1"Level
Ball "0..*" <-- "1" Level
Overlay "1" <-- "1" Level
DynamicScene <|.. Level
TileMapContainer <|.. Level
BrickTilemap "1" <-- "1" Level
TextEntity "1..*" <-- "1" Overlay
StaticScene <|.. MenuScene
MenuButton "1..*" <-- "1" MenuScene
TextEntity <|.. MenuButton
MouseEnterListener <|.. MenuButton
MouseExitListener <|.. MenuButton
MouseButtonPressedListener <|.. MenuButton
MenuButton <|-- QuitButton
MenuButton <|-- PlayButton
DynamicSpriteEntity <|.. Paddle
Collider <|.. Paddle
KeyListener <|.. Paddle
SceneBorderTouchingWatcher <|.. Paddle
MouseMovedListener <|.. Paddle
Newtonian <|.. Paddle
DynamicSpriteEntity <|.. Powerup
Collided <|.. Powerup
Newtonian <|.. Powerup
Powerup <|-- PowerupSlowdownBall
Powerup <|-- PowerupMultiball
Powerup <|-- PowerupExtraLife
DynamicSpriteEntity <|.. Brick
Collider <|.. Brick
Collided <|.. Brick
RandomNumber "1" <-- "1" Brick
Powerup "1" <-- "1" PowerupBrick
RandomNumber "1" <-- "1" PowerupBrick
Brick <|-- PowerupBrick
Brick <|-- SimpleBrick
TileMap <|.. BrickTilemap
DynamicSpriteEntity <|.. Ball
Collider <|.. Ball
Collided <|.. Ball
Newtonian <|.. Ball
RandomNumber "1" <-- "1" Ball
SceneBorderTouchingWatcher <|.. Ball
SceneBorderCrossingWatcher <|.. Ball
StaticScene <|.. GameOverScene
DynamicTextEntity <|.. OverlayText
TextEntity <|.. MainText
BrickTilemap <|-- GenerateBrickTileMap
@enduml